### ISSUE TITLE
Support for terminal hyperlinks

### ISSUE THREAD

**Issue by juanzolotoochin** [rodaine/table#23]
When using terminal hyperlinks with escape characters, the table width values get messed up:

```
package main

import (
	"fmt"

	"github.com/rodaine/table"
)

func main() {
	link := fmt.Sprintf("\033]8;;%s\033\\%s\033]8;;\033\\", "https://ubuntu.com", "Ubuntu")
	tbl := table.New("Name", "Version")
	tbl.AddRow("Ubuntu", "20.04")

	tbl = table.New("Name", "Version")
	tbl.AddRow("Ubuntu", "20.04")
	tbl.AddRow(link, "20.04")
	tbl.Print()
}
```

Output is

```
Name                                    Version  
Ubuntu                                  20.04    
Ubuntu  20.04    
```

When using a terminal that supports hyperlinks, the link gets rendered correctly, but the widths are still messed up (see underline in screenshot):
![image](https://user-images.githubusercontent.com/88746611/227041030-0125499b-276e-44b7-9b03-b887d56e1b5c.png)

![image](https://user-images.githubusercontent.com/88746611/227041109-bc57bc10-150e-46c2-a87b-7e3f041aa5f3.png)

```

**Comment by rodaine** [comment]
Hey, thanks for the feedback! TIL about terminal links which is a pretty sweet feature. You can probably achieve this by providing a custom `WidthFunc`.
