### ISSUE TITLE
Coloring rows distorts columns

### ISSUE THREAD

**Issue by smjure** [rodaine/table#42]
I'd like to color rows based on some if conditions. I came up with this minimal working example. Adding ANSI colors it seems does not work as expected, i.e. the columns get bit distorted (but without them its OK). Why? Could this be fixed or perhaps coloring rows added  as a new feature?
```
package main

import (
	"github.com/rodaine/table"
)

func main() {

	tbl := table.New("columnA", "columnB", "columnC")
	for i := 0; i < 10; i++ {
		color := "\033[34m"
		flg := i%2 != 0
		if flg {
			color = "\033[33m"
		}
		if flg {
			tbl.AddRow(color+"A", "B", "C"+"\033[0m")
		} else {
			tbl.AddRow(color+"A", "B", "C"+"\033[0m")
		}
	}
	tbl.Print()
}
```

**Comment by LukaszMoskala** [comment]
I'm also interested in this feature. Fortunately, all you need to do is use custom `WithWidthFunc`.

I'm using https://github.com/acarl005/stripansi to strip control characters before passing string to `utf8.RuneCountInString` which is default width function.

So it looks more or less like this:

```go
func ColorAwareWidth(s string) int {
	return utf8.RuneCountInString(stripansi.Strip(s))
}
...
tbl.WithWidthFunc(ColorAwareWidth)
```
and it seems to handle colors in columns well.

@rodaine maybe you could add mention about it to README if someone looks for this in the future.

**Comment by rodaine** [comment]
Good idea!

> maybe you could add mention about it to README if someone looks for this in the future.

Feel free to open a PR.
